config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'


 scope module: :public do
   get 'cosmetics/cezanne' => 'cosmetics#cezanne', as: 'cezanne'
   get 'cosmetics/integrate' => 'cosmetics#integrate', as: 'integrate'
   get 'cosmetics/canmake' => 'cosmetics#canmake', as: 'canmake'
   get 'cosmetics/eyebrow' => 'cosmetics#eyebrow', as: 'eyebrow'
   get 'cosmetics/eyeliner' => 'cosmetics#eyeliner', as: 'eyeliner'
   get 'cosmetics/mascara' => 'cosmetics#mascara', as: 'mascara'
   get 'cosmetics/eyeshadow' => 'cosmetics#eyeshadow', as: 'eyeshadow'
   get 'cosmetics/lip' => 'cosmetics#lip', as: 'lip'
   get 'cosmetics/base' => 'cosmetics#base', as: 'base'
   get 'cosmetics/cheek' => 'cosmetics#cheek', as: 'cheek'
   get 'cosmetics/foundation' => 'cosmetics#foundation', as: 'foundation'
   get 'cosmetics/powder' => 'cosmetics#powder', as: 'powder'
   resources :cosmetics do
      collection do
        get 'search'
      end
         resources :reviews do
         resources :comments
       end
   end

    get 'users/show' => 'users#show', as: 'my_page'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users' => 'users#update'
    patch 'users/out' => 'users#out', as: 'out'
  end

  namespace :admin do
    resources :users
    resources :skin_types
    resources :parsonal_colors
    resources :cosmetics
    resources :reviews
  end


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
    get 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :redirect_root


  def index
    @reviews = Review.all
    @reviews = Review.all.page(params[:page]).per(10)
  end

  def show

  end

  def destroy
    review = Review.find(params[:id])  # データ（レコード）を1件取得
    review.destroy
    redirect_to admin_reviews_path
  end

private
  def redirect_root
    redirect_to root_path unless admin_signed_in?
  end
  
  def review_params
    params.require(:review).permit(:user_id, :cosmetic_id, :review, :rate)
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/destroy.html.erb
<h1>Admin::Reviews#destroy</h1>
<p>Find me in app/views/admin/reviews/destroy.html.erb</p>

app/views/admin/reviews/index.html.erb
<h3>レビュー一覧</h3>
<table class="table" style="margin-top: 30px;">
  <thead>
    <tr>
        <th scope="col">レビューID</th>
        <th scope="col">化粧品名</th>
        <th scope="col">カラー</th>
        <th scope="col">投稿者</th>
        <th scope="col">評価</th>
        <th scope="col">レビュー</th>
        <th></th>
    </tr>
  </thead>
  <tbody>
      <% @reviews.each do |review| %>
      <tr>
          <td><%= review.id %></td>
          <td><%= review.cosmetic.name %></td>
          <td><%= review.cosmetic.color %></td>
          <td><%= review.user.nickname %></td>
          <td><div id="rate_<%= review.id %>"></div></td>
          <td><%= review.review %></td>
          <td><%= link_to "削除", admin_review_path(review.id), method: :delete, class:"btn btn-danger" %></td>
      </tr>

      <script>
        document.getElementById('rate_<%= review.id %>').innerHTML = '';
        raty(document.getElementById('rate_<%= review.id %>'), {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: <%= review.rate %>,
            readOnly: true,
          });
      </script>
      <% end %>
  </tbody>
  </table>
  <div class="d-flex justify-content-center">
  <%= paginate @reviews %>
 </div>

app/views/admin/reviews/show.html.erb
<h1>Admin::Reviews#show</h1>
<p>Find me in app/views/admin/reviews/show.html.erb</p>