config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'


 scope module: :public do
   get 'cosmetics/cezanne' => 'cosmetics#cezanne', as: 'cezanne'
   get 'cosmetics/integrate' => 'cosmetics#integrate', as: 'integrate'
   get 'cosmetics/canmake' => 'cosmetics#canmake', as: 'canmake'
   get 'cosmetics/eyebrow' => 'cosmetics#eyebrow', as: 'eyebrow'
   get 'cosmetics/eyeliner' => 'cosmetics#eyeliner', as: 'eyeliner'
   get 'cosmetics/mascara' => 'cosmetics#mascara', as: 'mascara'
   get 'cosmetics/eyeshadow' => 'cosmetics#eyeshadow', as: 'eyeshadow'
   get 'cosmetics/lip' => 'cosmetics#lip', as: 'lip'
   get 'cosmetics/base' => 'cosmetics#base', as: 'base'
   get 'cosmetics/cheek' => 'cosmetics#cheek', as: 'cheek'
   get 'cosmetics/foundation' => 'cosmetics#foundation', as: 'foundation'
   get 'cosmetics/powder' => 'cosmetics#powder', as: 'powder'
   resources :cosmetics do
      collection do
        get 'search'
      end
         resources :reviews do
         resources :comments
       end
   end

    get 'users/show' => 'users#show', as: 'my_page'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users' => 'users#update'
    patch 'users/out' => 'users#out', as: 'out'
  end

  namespace :admin do
    resources :users
    resources :skin_types
    resources :parsonal_colors
    resources :cosmetics
    resources :reviews
  end


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
    get 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/cosmetic.rb
class Cosmetic < ApplicationRecord
  has_one_attached :image
  has_many :reviews

  validates :name, presence: true
  validates :brand, presence: true
  validates :color, presence: true
  validates :source, presence: true
  
  
end

app/controllers/admin/cosmetics_controller.rb
class Admin::CosmeticsController < ApplicationController
  before_action :redirect_root

  def new
    @cosmetic = Cosmetic.new
  end

  def create
    @cosmetic = Cosmetic.new(cosmetic_params)
    if @cosmetic.save
      redirect_to admin_cosmetics_path
    else
      render template: "admin/cosmetics/new"
    end
  end

  def index
    @cosmetics = Cosmetic.all
    @cosmetics = Cosmetic.all.page(params[:page]).per(10)
  end

  def show
    @cosmetic = Cosmetic.find(params[:id])
  end

  def edit
    @cosmetic = Cosmetic.find(params[:id])
  end

  def update
    @cosmetic = Cosmetic.find(params[:id])
    if @cosmetic.update(cosmetic_params)
      redirect_to admin_cosmetic_path(@cosmetic.id)
    else
      render template: "admin/cosmetics/edit"
    end
  end

private
  def redirect_root
    redirect_to root_path unless admin_signed_in?
  end

  def cosmetic_params
    params.require(:cosmetic).permit(:name, :brand, :image, :color, :source)
  end
end

app/helpers/admin/cosmetics_helper.rb
module Admin::CosmeticsHelper
end

app/views/admin/cosmetics/edit.html.erb
<div class="container">
  <div class="row">
    <% if @cosmetic.errors.any? %>
      <%= @cosmetic.errors.count %>件のエラーが発生しました
      <ul>
        <% @cosmetic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="col-12">
      <h4>化粧品編集</h4>
      <div class="item" style="margin-top: 50px; font-size: 15px;">化粧品画像</div>
      <%= form_with model: @cosmetic, url:admin_cosmetic_path(@cosmetic.id) do |f| %>
        <div class="item">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">化粧品名</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :name %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">ブランド</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :brand %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">カラー</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :color %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">出典</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :source %></div>
        <div class="item" style="margin-top: 20px;"><%= f.submit '変更を保存', class:"btn btn-primary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/cosmetics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h3>化粧品一覧</h3>
    </div>
    <div class="col-2">
      <%= link_to "化粧品登録", new_admin_cosmetic_path, class:"btn btn-dark" %>
    </div>
    <table class="table" style="margin-top: 20px;">
      <thead>
        <tr>
          <th scope="col">化粧品ID</th>
          <th></th>
          <th scope="col">化粧品名</th>
          <th scope="col">カラー</th>
          <th scope="col">ブランド</th>
        </tr>
      </thead>
      <tbody>
        <% @cosmetics.each do |cosmetic| %>
          <tr>
            <td><%= cosmetic.id %></td>
            <td>
            　<%= link_to admin_cosmetic_path(cosmetic.id) do %>
                <% if cosmetic.image.attached? %>
                  <%= image_tag cosmetic.image, size: "50x50" %>
                <% else %>
                  <%= image_tag asset_path('default-image.jpg'), size: "50x50" %>
                <% end %>
              <% end %>
            </td>
            <td><%= cosmetic.name %></td>
            <td><%= cosmetic.color %></td>
            <td><%= cosmetic.brand %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @cosmetics %>
</div>

app/views/admin/cosmetics/new.html.erb
<div class="container">
  <div class="row">
    <% if @cosmetic.errors.any? %>
      <%= @cosmetic.errors.count %>件のエラーが発生しました
      <ul>
        <% @cosmetic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="col-12">
     <h4>化粧品新規登録</h4>
      <div class="item" style="margin-top: 50px; font-size: 15px;">化粧品画像</div>

      <%= form_with model: @cosmetic, url:admin_cosmetics_path do |f| %>
        <div class="item"><%= f.file_field :image, accept: "image/*" %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">化粧品名</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :name %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">カラー</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :color %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">ブランド</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :brand %></div>
        <div class="item" style="margin-top: 20px; font-size: 15px;">出典：</div>
        <div class="item" style="font-size: 15px;"><%= f.text_field :source %></div>
        <div class="item" style="margin-top: 20px;"><%= f.submit '新規登録', class:"btn btn-primary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/cosmetics/show.html.erb
<div class="container">
  <h4>化粧品詳細</h4>
  <div class="row">
    <div class="col-3" style="margin-left: 190px;">
      <% if @cosmetic.image.attached? %>
        <%= image_tag @cosmetic.image, size: "200x200" %>
      <% else %>
        <%= image_tag asset_path('default-image.jpg'), size: "200x200" %>
      <% end %>
    </div>

    <div class="col-1">
      <div class="item" style="margin-top: 30px; font-size: 15px;">化粧品名</div>
      <div class="item" style="margin-top: 20px; font-size: 15px;">ブランド</div>
      <div class="item" style="margin-top: 20px; font-size: 15px;">カラー</div>
      <div class="item" style="margin-top: 20px; font-size: 15px;">出典</div>
    </div>

    <div class="col-6">
      <div class="item" style="margin-top: 30px; font-size: 15px;"><%= @cosmetic.name %></div>
      <div class="item" style="margin-top: 20px; font-size: 15px;"><%= @cosmetic.brand %></div>
      <div class="item" style="margin-top: 20px; font-size: 15px;"><%= @cosmetic.color %></div>
      <div class="item" style="margin-top: 20px; font-size: 15px;"><%= @cosmetic.source %></div>
    </div>
  </div>

  <div class="item"><%= link_to "編集する", edit_admin_cosmetic_path(@cosmetic.id), class:"btn btn-primary" %></div>
</div>