config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'


 scope module: :public do
   get 'cosmetics/cezanne' => 'cosmetics#cezanne', as: 'cezanne'
   get 'cosmetics/integrate' => 'cosmetics#integrate', as: 'integrate'
   get 'cosmetics/canmake' => 'cosmetics#canmake', as: 'canmake'
   get 'cosmetics/eyebrow' => 'cosmetics#eyebrow', as: 'eyebrow'
   get 'cosmetics/eyeliner' => 'cosmetics#eyeliner', as: 'eyeliner'
   get 'cosmetics/mascara' => 'cosmetics#mascara', as: 'mascara'
   get 'cosmetics/eyeshadow' => 'cosmetics#eyeshadow', as: 'eyeshadow'
   get 'cosmetics/lip' => 'cosmetics#lip', as: 'lip'
   get 'cosmetics/base' => 'cosmetics#base', as: 'base'
   get 'cosmetics/cheek' => 'cosmetics#cheek', as: 'cheek'
   get 'cosmetics/foundation' => 'cosmetics#foundation', as: 'foundation'
   get 'cosmetics/powder' => 'cosmetics#powder', as: 'powder'
   resources :cosmetics do
      collection do
        get 'search'
      end
         resources :reviews do
         resources :comments
       end
   end

    get 'users/show' => 'users#show', as: 'my_page'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users' => 'users#update'
    patch 'users/out' => 'users#out', as: 'out'
  end

  namespace :admin do
    resources :users
    resources :skin_types
    resources :parsonal_colors
    resources :cosmetics
    resources :reviews
  end


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
    get 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/parsonal_color.rb
class ParsonalColor < ApplicationRecord
  has_many :users
  
  validates :color_name, presence: true
end

app/controllers/admin/parsonal_colors_controller.rb
class Admin::ParsonalColorsController < ApplicationController
  before_action :redirect_root

  def create
    @parsonal_color = ParsonalColor.new(parsonal_color_params)
    if @parsonal_color.save
      redirect_to '/admin/parsonal_colors'
    else
      @parsonal_colors = ParsonalColor.all
      render template: "admin/parsonal_colors/index"
    end
  end
  def edit
    @parsonal_color = ParsonalColor.find(params[:id])
  end

  def update
    @parsonal_color = ParsonalColor.find(params[:id])
    if @parsonal_color.update(parsonal_color_params)
      redirect_to '/admin/parsonal_colors'
    else
      render template: "admin/parsonal_colors/edit"
    end
  end

  def index
     @parsonal_color = ParsonalColor.new
     @parsonal_colors = ParsonalColor.all
  end

private
  def redirect_root
    redirect_to root_path unless admin_signed_in?
  end

  def parsonal_color_params
    params.require(:parsonal_color).permit(:color_name)
  end
end

app/helpers/admin/parsonal_colors_helper.rb
module Admin::ParsonalColorsHelper
end

app/views/admin/parsonal_colors/edit.html.erb
<div class="container">
  <div class="row">
    <% if @parsonal_color.errors.any? %>
      <%= @parsonal_color.errors.count %>件のエラーが発生しました
      <ul>
        <% @parsonal_color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="col-6">
      <h3>パーソナルカラー編集</h3>
      <%= form_with model: @parsonal_color,url:admin_parsonal_color_path(@parsonal_color.id) do |f| %>
        <div class="row">
          <div class="item col-4" style="margin-top: 30px; font-size:15px;">パーソナルカラー名</div>
          <div class="item col-3" style="margin-top: 30px; font-size:15px;"><%= f.text_field :color_name %></div>
          <div class="item col-1" style="margin-top: 30px;"><%= f.submit '保存', class:"btn btn-primary" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/parsonal_colors/index.html.erb
<div class="container">
  <div class="row">
    <% if @parsonal_color.errors.any? %>
      <%= @parsonal_color.errors.count %>件のエラーが発生しました
      <ul>
        <% @parsonal_color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="col-6">
    <h3>パーソナルカラー一覧・追加</h3>
      <%= form_with model: @parsonal_color, url:admin_parsonal_colors_path do |f| %>
        <div class="row">
          <div class="item col-2" style="margin-top: 30px; margin-left: 100px; font-size:15px;"><%= f.text_field :color_name %></div>
          <div class="item col-2" style="margin-top: 30px; margin-left: 10px"><%= f.submit '登録', class:"btn btn-primary" %></div>
        </div>
      <% end %>

      <table class="table" style="margin-top: 50px;">
        <thead>
          <tr>
            <th>パーソナルカラー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @parsonal_colors.each do |parsonal_color| %>
            <tr>
              <td><%= parsonal_color.color_name %></td>
              <td><%= link_to "編集", edit_admin_parsonal_color_path(parsonal_color.id), class:"btn btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>