config/routes.rb
Rails.application.routes.draw do

root to: 'public/homes#top'


 scope module: :public do
   get 'cosmetics/cezanne' => 'cosmetics#cezanne', as: 'cezanne'
   get 'cosmetics/integrate' => 'cosmetics#integrate', as: 'integrate'
   get 'cosmetics/canmake' => 'cosmetics#canmake', as: 'canmake'
   get 'cosmetics/eyebrow' => 'cosmetics#eyebrow', as: 'eyebrow'
   get 'cosmetics/eyeliner' => 'cosmetics#eyeliner', as: 'eyeliner'
   get 'cosmetics/mascara' => 'cosmetics#mascara', as: 'mascara'
   get 'cosmetics/eyeshadow' => 'cosmetics#eyeshadow', as: 'eyeshadow'
   get 'cosmetics/lip' => 'cosmetics#lip', as: 'lip'
   get 'cosmetics/base' => 'cosmetics#base', as: 'base'
   get 'cosmetics/cheek' => 'cosmetics#cheek', as: 'cheek'
   get 'cosmetics/foundation' => 'cosmetics#foundation', as: 'foundation'
   get 'cosmetics/powder' => 'cosmetics#powder', as: 'powder'
   resources :cosmetics do
      collection do
        get 'search'
      end
         resources :reviews do
         resources :comments
       end
   end

    get 'users/show' => 'users#show', as: 'my_page'
    get 'users/edit' => 'users#edit'
    get 'users/confirm' => 'users#confirm', as: 'confirm'
    patch 'users' => 'users#update'
    patch 'users/out' => 'users#out', as: 'out'
  end

  namespace :admin do
    resources :users
    resources :skin_types
    resources :parsonal_colors
    resources :cosmetics
    resources :reviews
  end


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
    get 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COSMEnavi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-white">
        <%= link_to root_path, class: "top" do %>
          <h1>COSMEnavi<%= image_tag 'rouge2.png', size: "30x30" %></h1>
        <% end %>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <% if user_signed_in? %>
            <div class="p-2">
              <%= link_to cosmetics_path, class: "btn btn--header btn--cubic btn--shadow" do %>
                <i class="fa fa-heart" style="color: white;" ></i> すべての化粧品
              <% end %>
            </div>

            <div class="p-2">
              <%= link_to my_page_path, class: "btn btn--header btn--cubic btn--shado" do %>
                <i class="fa fa-user" style="color: white;" ></i> マイページ
              <% end %>
            </div>

            <div class="p-2">
              <%= link_to destroy_user_session_path, method: :delete, class: "btn btn--header btn--cubic btn--shado" do %>
                <i class="fas fa-sign-out-alt" style="color: white;" ></i> ログアウト
              <% end %>
            </div>

          <% elsif admin_signed_in? %>
            <div class="p-2">
              <%= link_to admin_skin_types_path, class: "btn btn--header btn--cubic btn--shadow" do %>肌タイプ一覧
              <% end %>
            </div>
            <div class="p-2">
              <%= link_to admin_parsonal_colors_path, class: "btn btn--header btn--cubic btn--shadow" do %>パーソナルカラー一覧
              <% end %>
            </div>
            <div class="p-2">
              <%= link_to admin_cosmetics_path, class: "btn btn--header btn--cubic btn--shadow" do %>化粧品一覧
              <% end %>
            </div>
            <div class="p-2">
              <%= link_to admin_users_path, class: "btn btn--header btn--cubic btn--shadow" do %>会員一覧
              <% end %>
            </div>
            <div class="p-2">
              <%= link_to admin_reviews_path, class: "btn btn--header btn--cubic btn--shadow" do %>レビュー一覧
              <% end %>
            </div>
            <div class="p-2">
              <%= link_to destroy_admin_session_path, method: :delete, class: "btn btn--header btn--cubic btn--shadow" do %>ログアウト
              <% end %>
            </div>
          <% else %>
            <div class="p-2">
              <%= link_to new_user_registration_path, class: "btn btn--header btn--cubic btn--shadow" do %>新規登録
              <% end %>
            </div>
            <div class="p-2">
              <%= link_to  new_user_session_path, class: "btn btn--header btn--cubic btn--shadow" do %>ログイン
              <% end %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>